In [145]:
features = ['atvType', 'make', 'model', 'year', 'cityE', 'evMotor', 'highwayE', 'combE', 'range', 'rangeCity', 
            'rangeHwy', 'c240Dscr', 'c240bDscr', 'charge240', 'charge240b']
df = pd.read_csv('vehicles.csv', usecols=features, dtype={'evMotor' : 'str', 'c240Dscr' : 'str', 'c240bDscr': 'str'})
df.shape

(37241, 15)

In [88]:
df.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA',
       'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn

In [146]:
# df_ev = df.query("atvType == 'EV' | atvType == 'Plug-in Hybrid'")
df_ev = df[df.atvType == 'EV']
df_ev.head()

charge240  cityE  combE  highwayE    make                   model  \
7138        0.0   41.0   40.0      37.0  Nissan                Altra EV   
7139        0.0   41.0   47.0      53.0  Toyota                 RAV4 EV   
8143        0.0   41.0   47.0      53.0  Toyota                 RAV4 EV   
8144        0.0   46.0   52.0      59.0    Ford                   Th!nk   
8146        0.0   75.0   87.0     102.0    Ford  Explorer USPS Electric   

      range  rangeCity  rangeHwy  year atvType             evMotor c240Dscr  \
7138     90        0.0       0.0  2000      EV  62 KW AC Induction      NaN   
7139     88        0.0       0.0  2000      EV            50 KW DC      NaN   
8143     88        0.0       0.0  2001      EV            50 KW DC      NaN   
8144     29        0.0       0.0  2001      EV  27 KW AC Induction      NaN   
8146     38        0.0       0.0  2001      EV  67 KW AC Induction      NaN   

      charge240b c240bDscr  
7138         0.0       NaN  
7139         0.0       NaN  
8143         0.0       NaN  
8144         0.0       NaN  
8146         0.0       NaN

In [140]:
df_ev[df_ev.year>2005].head(10)

charge240  cityE  combE  highwayE             make  \
23040       0.0   33.0   34.0      36.0             MINI   
23041       7.0   32.0   34.0      37.0           Nissan   
23137       8.0   36.0   39.0      43.0            smart   
23138       8.0   36.0   39.0      43.0            smart   
23807       7.0   27.0   30.0      34.0       Mitsubishi   
24051       8.0   55.0   54.0      54.0   Azure Dynamics   
24052       8.0   55.0   54.0      54.0   Azure Dynamics   
24341       7.0   32.0   34.0      37.0           Nissan   
24472       5.0   32.0   33.0      35.0              BMW   
24473       6.0   44.0   46.0      50.0  CODA Automotive   

                                 model  range  rangeCity  rangeHwy  year  \
23040                            MiniE    100     0.0000    0.0000  2008   
23041                             Leaf     73     0.0000    0.0000  2011   
23137  fortwo electric drive cabriolet     63     0.0000    0.0000  2011   
23138      fortwo electric drive coupe     63     0.0000    0.0000  2011   
23807                           i-MiEV     62    68.5545   54.8184  2012   
24051     Transit Connect Electric Van     56    56.7812   55.6759  2012   
24052   Transit Connect Electric Wagon     56    56.7812   55.6759  2012   
24341                             Leaf     73    77.1650   67.3160  2012   
24472                         Active E     94     0.0000    0.0000  2011   
24473                             CODA     88    93.5550   93.5550  2012   

      atvType              evMotor c240Dscr charge240b c240bDscr  
23040      EV               150 kW      NaN        0.0       NaN  
23041      EV           80 kW DCPM      NaN        0.0       NaN  
23137      EV           30 kW DCPM      NaN        0.0       NaN  
23138      EV           30 kW DCPM      NaN        0.0       NaN  
23807      EV           49 kW DCPM      NaN        0.0       NaN  
24051      EV   52 kW AC Induction      NaN        0.0       NaN  
24052      EV   52 kW AC Induction      NaN        0.0       NaN  
24341      EV           80 kW DCPM      NaN        0.0       NaN  
24472      EV  125 kW AC Induction      NaN        0.0       NaN  
24473      EV          100 kW DCPM      NaN        0.0       NaN

In [96]:
df_ev[df_ev.atvType == 'EV'].c240Dscr.unique()

array([nan, 'single charger', '3.6 kW charger', 'standard charger',
       '7.2 kW charger', '6.6 kW charger'], dtype=object)

In [97]:
df_ev[df_ev.atvType == 'EV'].c240bDscr.unique()

array([nan, 'dual charger', '6.6 kW charger', '80 amp dual charger',
       '3.6 kW charger'], dtype=object)

In [106]:
df_ev.atvType.unique()

array([nan, 'Diesel', 'Hybrid', 'Bifuel (CNG)', 'CNG', 'FFV', 'EV',
       'Bifuel (LPG)', 'Plug-in Hybrid'], dtype=object)

In [171]:
df_ev['batteryC'] = df_ev['range'] * df_ev['combE'] /100
df_ev['chargeP'] = df_ev['range'] * df_ev['combE'] /100 / df_ev['charge240']
df_ev['chargePb'] = df_ev['range'] * df_ev['combE'] /100 / df_ev['charge240b']
df_ev = df_ev.replace([np.inf, -np.inf], np.nan)
df_ev['acceptanceR'] = df_ev[['chargeP', 'chargePb']].max(axis=1)
df_ev[df_ev['year']>2014].head(10)

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pa

charge240    cityE    combE  highwayE           make  \
27386        8.0  26.6482  29.6225   33.2577         Nissan   
27612        7.0  26.2638  28.3449   30.8654      Chevrolet   
27706        4.0  27.5370  29.1733   31.1733           Fiat   
28144        4.0  28.1744  31.9856   36.6438            Kia   
28417        4.0  26.8395  29.1683   32.0146     Volkswagen   
28427        6.0  27.7043  31.5042   36.1486          smart   
28428        6.0  27.7043  31.5042   36.1486          smart   
28541        3.5  39.0000  40.0000   41.0000  Mercedes-Benz   
28552        3.6  31.0000  32.0000   34.0000           Ford   
28563       12.0  38.0000  38.0000   37.0000          Tesla   

                                   model  range  rangeCity  rangeHwy  year  \
27386                               Leaf     84    92.0000   74.0000  2015   
27612                           Spark EV     82    87.8000   74.8000  2015   
27706                               500e     87    91.8400   81.4800  2015   
28144                      Soul Electric     93   148.0000  113.8000  2015   
28417                             e-Golf     83    88.9000   75.2000  2015   
28427  fortwo electric drive convertible     68    76.0000   59.0000  2015   
28428        fortwo electric drive coupe     68    76.0000   59.0000  2015   
28541             B-Class Electric Drive     87    89.0000   85.0000  2015   
28552                     Focus Electric     76    79.7573   71.5259  2015   
28563    Model S (85 kW-hr battery pack)    265   262.7000  266.8000  2015   

      atvType                                      evMotor          c240Dscr  \
27386      EV                                   80 kW DCPM    3.6 kW charger   
27612      EV                                  104 kW ACPM               NaN   
27706      EV                           82 kW AC Induction               NaN   
28144      EV                                81 kW AC PMSM               NaN   
28417      EV                                85 kW AC PMSM               NaN   
28427      EV                                   55 kW DCPM               NaN   
28428      EV                                   55 kW DCPM               NaN   
28541      EV                          132 kW AC Induction               NaN   
28552      EV                               107 kW AC PMSM               NaN   
28563      EV  270 kW AC Induction (85 kW-hr battery pack)  standard charger   

       charge240b            c240bDscr   chargeP  chargePb    batteryC  \
27386        5.00       6.6 kW charger  3.110362   4.97658   24.882900   
27612        0.00                  NaN  3.320403       NaN   23.242818   
27706        0.00                  NaN  6.345193       NaN   25.380771   
28144        0.00                  NaN  7.436652       NaN   29.746608   
28417        0.00                  NaN  6.052422       NaN   24.209689   
28427        0.00                  NaN  3.570476       NaN   21.422856   
28428        0.00                  NaN  3.570476       NaN   21.422856   
28541        0.00                  NaN  9.942857       NaN   34.800000   
28552        0.00                  NaN  6.755556       NaN   24.320000   
28563        4.75  80 amp dual charger  8.391667  21.20000  100.700000   

       acceptanceR  
27386     4.976580  
27612     3.320403  
27706     6.345193  
28144     7.436652  
28417     6.052422  
28427     3.570476  
28428     3.570476  
28541     9.942857  
28552     6.755556  
28563    21.200000

In [172]:
import sqlite3
with sqlite3.connect('ev_model.db') as conn:
    df_ev[df_ev['acceptanceR']>0].to_sql('spec', conn, if_exists='replace')

In [174]:
def select_models(n):
    cur.execute('SELECT acceptanceR, model, make FROM spec LIMIT ?', (n, ))
    for row in cur:
        print(row)

conn = sqlite3.connect('ev_model.db')
cur = conn.cursor()
select_models(10)

(3.545714285714286, 'Leaf', 'Nissan')
(3.07125, 'fortwo electric drive cabriolet', 'smart')
(3.07125, 'fortwo electric drive coupe', 'smart')
(2.6571428571428575, 'i-MiEV', 'Mitsubishi')
(3.78, 'Transit Connect Electric Van', 'Azure Dynamics')
(3.78, 'Transit Connect Electric Wagon', 'Azure Dynamics')
(3.545714285714286, 'Leaf', 'Nissan')
(6.204, 'Active E', 'BMW')
(6.746666666666666, 'CODA', 'CODA Automotive')
(6.08, 'Focus Electric', 'Ford')
